name = input()
sname = input()
print("Hello " + name + " " + sname + "! You just delved into Python") 
print("Hello %s %s! You just delved into Python"%(name, sname))
print(f"Hello {name} {sname}! You just delved into Python")
